version: "3.9"

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server
  server:
    restart: always
    container_name: server
    image: server
    build:
      context: ./src/server
      dockerfile: backend.dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      MYSQL_USER: swe
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: swe
      MYSQL_DATABASE: CINEMA
    ports:
      - 3306:3306
    volumes:
      - pgdata:/var/lib/mysqlql/data

volumes:
  pgdata: {}
