version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - MYSQL_DB=transteven
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - PGDATA=/data/mysql
    volumes:
      - db:/data/mysql

  cinema-backend:
    container_name: cinema-backend
    image: transteven/cinema-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:5432/user
    ports:
      - 8443:8443
    depends_on:
      - db
    networks:
      - db
    restart: always
  cinema-frontend:
    container_name: cinema-frontend
    image: transteven/cinema-frontend
    build:
      context: cinema/client
    args:
      api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - cinema-backend
    restart: always

  networks:
    db:
      driver: bridge

  volumes:
    db:
