version: "3.9"

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always
    depends_on:
      - server
  server:
    container_name: server
    image: server
    build:
      context: ./src/server
      dockerfile: server.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=jdbc:mysql://5432:4000/CINEMA
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_USER: CINEMA_USERNAME
      MYSQL_PASSWORD: CINEMA_USER_PASSWORD
      MYSQL_DATABASE: CINEMA
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/mysqlql/data

volumes:
  pgdata: {}
