version: "3.8"

services:
  db:
    container_name: db
    image: mysql:8.3.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: cinema
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  server:
    container_name: server
    image: server
    build: server
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]

  frontend:
    container_name: frontend
    image: frontend
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      server:
        condition: service_healthy